name: OceanBase Ecosystem Plugins CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flyway-plugin:
    name: Build Flyway OceanBase Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Flyway Plugin
        run: |
          cd flyway-oceanbase-plugin
          ./mvnw clean package -DskipTests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flyway-oceanbase-plugin
          path: flyway-oceanbase-plugin/target/*.jar

  trino-plugin:
    name: Build Trino OceanBase Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build Trino Plugin
        run: |
          cd trino-oceanbase-plugin
          ./mvnw clean install -DskipTests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trino-oceanbase-plugin
          path: trino-oceanbase-plugin/target/*.jar

  wordpress-plugin:
    name: Build WordPress OceanBase Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-oceanbase-plugin
          path: wordpress-oceanbase-plugin/*.zip